# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KakaoLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'KakaoSDKCommon'
  # Pods for KakaoLogin

end
